### ISSUE TITLE
This seems to be a duplicate

### ISSUE THREAD

**Issue by nobody5050** [MCPI-Devs/proxy#1]
This repo seems to be a duplicate of [mcbes.](https://github.com/mcbes). If you’d like to fork mcbes into this org or include it natively as a mirror please do. I’d also like to join the org if possible i have a few ideas for your launcher.

**Comment by torralbaa** [comment]
Ok, first of all, this project is older than  MCBes, and you can track the previous development in the [MCPIL](https://github.com/Alvarito050506/MCPIL) repository. Second, I didn't use any code of MCBes. Third, the aim of this project is completly different. This project aims to be a proxy between MCPI/MCPI 0.6.1 servers and clients, not between MCPI and newer versions. And finally, I'll think about it, since this issue demostrates something I don't like.

**Comment by torralbaa** [comment]
I will close the issue because it is irrelevant, but I will not lock the conversation, because feedback and discussion is still appreciated.

**Comment by nobody5050** [comment]
super sorry, i misread this. you can keep this closed and lock as no further discussion is warranted

**Comment by torralbaa** [comment]
Don't worry. And sorry if I was a bit rude, I didn't know you just misread this...
